cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
     path('addtocart/<p>',views.add_to_cart,name="addtocart"),
     path('cartview',views.cartview,name="cartview"),
path('cart_remove/<p>',views.cart_remove,name="cart_remove"),
path('full_remove/<p>',views.full_remove,name="full_remove"),
path('orderform',views.orderform,name="orderform"),
path('orderview',views.orderview,name="orderview"),

]

ira/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
]
if (settings.DEBUG):
  urlpatterns += static (settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
path('search',views.search,name="search"),
]

shop/urls.py
from django.urls import path
from shop import views
app_name="shop"




urlpatterns = [
       path('',views.allcategories,name="allcat"),
path('allproducts/<p>',views.allproducts,name="allproducts"),
path('detail/<p>',views.detail,name="detail"),
    path('reg', views.register, name="register"),
    path('login', views.user_login, name="login"),
path('logout', views.user_logout, name="logout"),
]

cart/models.py
from django.db import models

# Create your models here.
from shop.models import Product
from django.contrib.auth.models import User


class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity * self.product.price


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    noofitems = models.IntegerField()
    address = models.TextField()
    phone = models.CharField(max_length=30)
    order_status = models.CharField(max_length=20, default="pending")
    delivery_status = models.CharField(max_length=20, default="pending")
    date_ordered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Account(models.Model):
    acctnum = models.CharField(max_length=20)
    accttype = models.CharField(max_length=20)
    amount = models.IntegerField()

    def __str__(self):
        return self.acctnum

search/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    image=models.ImageField(upload_to='categories/',blank=True,null=True)
    
    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    image=models.ImageField(upload_to='shop/products',blank=True,null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart,Account,Order


def cartview(request):

    total=0
    u=request.user
    try:
        cart=Cart.objects.filter(user=u)
        for i in cart:
            total+=i.quantity*i.product.price
    except:
        pass
    return render(request,'cart.html',{'c':cart,'total':total})
# Create your views here.
@login_required
def add_to_cart(request,p):
    product=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(product=product,user=u)
        if(cart.quantity<cart.product.stock):
            cart.quantity+=1
        cart.save()
    except:
        cart=Cart.objects.create(product=product,user=u,quantity=1)
        cart.save()
    return redirect('cart:cartview')


@login_required
def cart_remove(request,p):
    product=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(product=product,user=u)
        if cart.quantity>1:
            cart.quantity-=1
            cart.save()
        else:
             cart.delete()
    except:
        pass
    return redirect('cart:cartview')

def full_remove(request,p):
    product=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(product=product,user=u)
        cart.delete()
    except:
        pass
    return redirect('cart:cartview')


def orderform(request):
    if(request.method=="POST"):
        a=request.POST['a']
        p = request.POST['p']
        n = request.POST['n']
        u=request.user
        cart=Cart.objects.filter(user=u)

        total = 0
        for i in cart:
                total += i.quantity * i.product.price
        ac=Account.objects.get(acctnum=n)
        if (ac.amount>=total):
            ac.amount=ac.amount-total
            ac.save()

            for i in cart:# creates record in order table for each object in cart table for the current user
                o=Order.objects.create(user=u,product=i.product,address=a,phone=p,noofitems=i.quantity,order_status="paid")
                o.save()
                i.product.stock=i.product.stock-i.quantity
                i.product.save()
            cart.delete()#clears the cart after placement
            msg="Order Placed Successfully"
            return render(request,'orderdetail.html',{'m':msg})


        else:
            msg="Insufficient Amount in User Account.You cannot place Order."
            return render(request, 'orderdetail.html', {'m': msg})

    return render(request,'orderform.html')


def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview..html',{'u':u.username,'o':o})

# Create your views here.

search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

# Create your views here.
def search(request):
    q=""
    product=None
    if(request.method=="POST"):
        q=request.POST['q']
        if q:
            product=Product.objects.filter(Q(name__icontains=q)|Q(desc__icontains=q))
    return render(request, 'search.html',{'p':product,'query':q})

shop/views.py
import django.shortcuts
from django.shortcuts import render,redirect
from shop.models import Category,Product
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=Product.objects.filter(category=c)
    categories=Category.objects.all()
    return render(request, 'product.html', {'c': c,'p':p,'categories':categories})
 
   
def detail(request,p):
    product=Product.objects.get(name=p)
    return render(request, 'detail.html', {'p':product})

def register(request):
        if (request.method == "POST"):
            u = request.POST['u']
            p = request.POST['p']
            cp = request.POST['cp']
            e = request.POST['e']
            if (p == cp):
                u = User.objects.create_user(username=u, password=p, email=e)
                u.save()
                return redirect('shop:allcat')
            else:
                return HttpResponse("password not matching")
        return render(request, 'register.html')


def user_login(request):
    if (request.method == "POST"):
        user = request.POST['u']
        passw = request.POST['p']
        user = authenticate(username=user, password=passw)

        if user:
            login(request, user)
            return redirect('shop:allcat')

        else:
            messages.error(request, "invalid user")
    return render(request, 'login.html')

@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Ira shopping</title>
        <!-- Favicon-->
         
        <link rel="icon" type="image/x-icon" href="static/assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- Bootstrap JS Bundle with Popper -->
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="static/assets/css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        
       <div style="background-color:#80004c; height:70px;"> <center> <h5 style="color:white; font-size:30px; padding-top:10px;">Welcome{{u}} to the world of shopping! </h5>
        </center> </div>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#ede9da ">{% if not is_base.html %}
        
           <div class="back-button" style="padding-left:30px; "> <a href="javascript:history.back()" style="background-color:#80004c" class="btn btn-secondary">&larr;</a></div>
       
        {% endif %} 
           <div class="container px-4 px-lg-5" ><img src="{% static 'images/logo.jpeg' %}" height="40px" width="100px"  class="m-2">
               <h3 style=" color:#80004c; padding-left:15px; padding-top:20px;" ><strong>IRA FASHION</strong> </h3>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                 <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4" style="padding-top:10px; font-size:18px;">
                       
                        <li class="nav-item" ><a class="nav-link" style="color:#80004c; padding-left:200px; " aria-current="page" href="{% url 'shop:allcat' %}"><strong>Home</strong></a></li>
                        
                       

                       
                     

                       
                        {% if user.is_authenticated %}
                       
                       
              
                       <li class="nav-item">
                       <a class="nav-link" aria-current="page" style="color:#80004c;"  href="{% url  'shop:logout' %}"><strong>Logout</strong></a>
                     </li>
             
                     {% else %}
                   <li class="nav-item">
                       <a class="nav-link" aria-current="page" style="color:#80004c;"  href="{% url  'shop:register' %}"><strong>Register</strong></a>
                     </li>
                     <li class="nav-item">
                       <a class="nav-link" aria-current="page" style="color:#80004c;" href="{% url  'shop:login' %}"><strong>Login</strong></a> </li>
                     {% endif %}
                    </ul>  
                      </ul>
                    <form class="d-flex" method="POST" action="{% url 'search:search' %}">
                        {% csrf_token %}
                        
                        <input class="form-control me-2" name="q" type="search" style="width:400px;" placeholder=" 🔍 Try saree,kurthi or search what you want" aria-label="Search">
                       
                      </form>
                    
                      {% if user.is_authenticated %}
                      <form class="d-flex" >
                          <button class="btn btn-outline-dark" type="submit">
                              
                        <a class="nav-link nav-item" aria-current="page" href="{% url 'cart:cartview' %}">Cart
                          <i class="bi-cart-fill me-1" aria-hidden="true"></i>&nbsp;&nbsp;{{count}}</a>
                     
                          </button>
                      </form>


                    
              
                    {% endif %}
                </div>
            </div>
        </nav>
        
        <!-- Section-->{% block content %}
        
                                  {% endblock %}
                            
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="static/assets/js/scripts.js"></script>
    </body>
</html>
<footer>

    <div class="mt-5 footer " style="  height:50px;
  width:100%;
  background-color:white;
  position:fixed;
  bottom:0;
  left:0;
  text-align:center;">
  
      <p style="padding-top:10px;  font-weight:bold; "><i class="fa-regular fa-copyright"></i> irashop.com 2024, All Rights Reserved</p>
    </div>
    
    </footer>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not c %}
<div class="container mt-3">
<h3 class="text-center">Cart is empty</h3>
<h5 class="text-center text-success"><a href="{% url 'shop:allcat' %}">Continue Shopping</a></h5>
</div>
{% else %}
<div class="container-fluid m-3">
<div class="row">
    <h3 class="text-center text-danger">SHOPPING CART</h3>
    <div class="col-sm-6">
        <table class="table table-bordered">
            <tr><th colspan="5"> CART ITEMS</th></tr>
            {% for i in c %}
            <tr>
                <td><img src="{{i.product.image.url}}" height="100px" width="100px"></td>
                <td><b >{{i.product.name}}</b></td>
                 <td><b>₹{{i.product.price}}</b><br>
                     <b class="text-danger">Usually ship within 2 to 3 days</b><br>
                                      <b>Quantity:{{i.quantity}}*{{i.product.price}}</b></td>

                <td>
                    {% if i.quantity < i.product.stock %}
                    <a href="{% url 'cart:addtocart' i.product.name %}"><i style="color:black" class="bi bi-plus-circle" aria-hidden="true"></i></a>
                    <a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black" class="bi bi-dash-circle-fill" aria-hidden="true"></i></a><br><br>
                    <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black" class="bi bi-trash3-fill" aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                      </svg></i></a>
                    
           {% else %}
                    <a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black" class="bi bi-dash-circle-fill" aria-hidden="true"></i></a><br><br>
                    <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black" class="bi bi-trash3" aria-hidden="true"></i></a>
                </td>
                {% endif %}
                <td><b>Total:₹{{i.subtotal}}</b>
            </td>
         {% endfor %}
        </table>
        </div>

    <div class="col-sm-4" style="position:relative"><table class="table table-bordered" ><tr>
        <th colspan="4" class="text-center">CHECKOUT</th></tr>
    <tr><td class="text-center"><b>TOTAL: <span class="text-danger"> {{total}}</span></b></td></tr>
    </table>
        <h3><a href="{% url 'cart:orderform' %}"   class="btn btn-danger "><b>Place Order</b></a>
        <a href="{% url 'shop:allcat' %}" class="btn btn-danger " style="position:absolute;right:0;"><b>Continue Shopping</b></a></h3>
</div></div></div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid mt-4">
  <div class="row text-center">
      <!-- Loop through your categories -->

      {% for c in categories %}
          <div class="col-1 mx-3">
              <a href="{% url 'shop:allproducts' c.name %}" class="category-link">
                  <div class="category-card" style=" border: 1px solid #ddd;">
                      <img src="{{ c.image.url }}" alt="{{ c.name }}" class="img-fluid" style="height:70px; width:70px;">
                      <h6 class="mt-2" style="color:black; text-decoration:none;">{{ c.name }}</h6>
                  </div>
              </a>
          </div>
      {% endfor %}
  </div>
</div> 

</div>
<header class="py-1" style="width:100%;">
    <div class="container px-4 px-lg-5 my-5" style="background-color:white;  ">
        <div class="text-center text-white">
            <div id="carouselExample" class="carousel slide" data-bs-ride="carousel" data-bs-interval="2000">
                <div class="carousel-indicators">
                  <button type="button" data-bs-target="{% url 'shop:allcat' %}" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                  <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="1" aria-label="Slide 2"></button>
                  <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="2" aria-label="Slide 3"></button>
                  <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="3" aria-label="Slide 4"></button>
                </div>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="static\assets\img1.jpg" class="d-block w-100" alt="Slide 1">
                  </div>
                  <div class="carousel-item">
                    <img src="static\images\img5.jpg" class="d-block w-100" alt="Slide 2">
                  </div>
                  <div class="carousel-item">
                    <img src="static\images\img6.jpg" class="d-block w-100" alt="Slide 3">
                </div>
               
                <div class="carousel-item">
                    <img src="static\images\img7.jpg" class="d-block w-100" alt="Slide 4">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
            
            
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
  <center><h3>Explore what you need!</h3></center>
<center> <img src="static/images/logo.jpeg" height="80px" width="180px" class="m-2">
 </center>
    <div class="container mt-4">
       
        <div class="row">
            {% for i in c %}
                <div class="col-md-4 mb-4"> <!-- Each category will take 1/3rd of the row -->
                    <div class="card h-80" style="width:28rem;">
                        <img src="{{ i.image.url }}" class="card-img-top p-2" alt=".." height="350px" width="100%">
                        <div class="card-body">
                            <center><h5  class="card-title">{{ i.name }}</h5></center>
                            <p class="card-text">{{ i.description }}</p>
                            <a href="{% url 'shop:allproducts' i.name %}" class="btn btn-danger" style="position:relative;left:30%; background-color:#80004c ">Explore the Product</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div></section>

{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container mt-2 rounded rounded-5" style="margin-bottom:60px; margin-left:250px;">
    <div class="row">
        <div class="col-sm-4">
            <img src="{{p.image.url}}" alt=".." height="400px" width="400px"></div>
            <div class="col-sm-5">
                <h4>{{p.name}}</h4>
                <p class="mt-2">{{p.desc}}</p>
                <h5 class="mt-4">{{p.price}}</h5>
                <h4><a href="{% url 'cart:addtocart' p.name %}" class="btn btn-danger" style="background-color:#80004c;">Add to Cart</a></h4>
            </div>
            </div>
    </div>
        {% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center><h2 style="color:#80004c;">Login to view your profile</h2>
<form method="POST" >
{% csrf_token %}
<center><img src="static/images/login.webp" height="250px" width="480px" class="m-2">
  <div class="col-md-4">
    
    <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="enter the username">
  </div>

  <div class="col-md-4">
    <label  class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="enter the password">
  </div>
  <div class="col-md-4"style="padding-top:10px;">

    <input type="submit" class="form-control btn btn-danger " style="background-color:#80004c ">
  </div>

  <p style="padding-top:80px;">By continuing, you agree to irafashion's 
    Terms & Conditions  
    and  
    Privacy Policy</p>
</form>
{% if messages %}
{% for i in messages %}
<ul>
  <li>{{i}}</li>

</ul>
{% endfor %}
{% endif %}

{% endblock %}</center>

templates/logout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<body>
<h1>THANK YOU FOR SHOPPING</h1>
</body>
{% endblock %}

templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-5">
    <center>
        
        <h1 class="text-center" style="color:#80004c;">Congratulations<br>{{m}}</h1>
        <h4 class="text-center text-primary">Product will deliver sep 13</h4>
        <h2 class="text-center text-primary">Thank You For Shopping....</h2>
        <h5><a href="{% url 'shop:allcat' %}">Continue Shopping</a></h5>
        

    </center>
</div>
{% endblock %}

templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center> <h2 style="color:#80004c;">Enter Order Details</h2>
<form method="POST" >
{% csrf_token %}

 <div class="col-md-4">
    <label  class="form-label">Address</label>
    <input type="text" class="form-control" name="a" placeholder="Enter the address">
  </div>

  <div class="col-md-4">
    <label  class="form-label">Phone</label>
    <input type="text" class="form-control" name="p" placeholder="Enter the Phone Number">
  </div>
      <div class="col-md-4">
    <label  class="form-label">Account Number</label>
    <input type="text" class="form-control" name="n" placeholder="Enter the Account Number">
  </div>
              <div class="col-md-4"style="padding-top:10px;">

    <input type="submit" class="form-control btn btn-danger" style="background-color:#80004c;" >
  </div>
</form></center>
{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row text-center">
        <!-- Loop through your categories -->

        {% for c in categories %}
            <div class="col-1 mx-3">
                <a href="{% url 'shop:allproducts' c.name %}" class="category-link">
                    <div class="category-card" style=" border: 1px solid #ddd;">
                        <img src="{{ c.image.url }}" alt="{{ c.name }}" class="img-fluid" style="height:70px; width:70px;">
                        <h6 class="mt-2" style="color:black; text-decoration:none;">{{ c.name }}</h6>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
<center><div class="container-fluid mt-4" style="margin-bottom:100px;">
   
    
    <img src="{{ c.image.url }}" height="600px" width="70%"  >
</div></center>

   <center> <h3 style="color:#80004c;"class="text-center">{{c.name}}</h3></center><center><img src="{% static 'images/logo.jpeg' %}" height="80px" width="180px" class="m-2">
</center>
    <div class="container-fluid mt-1 rounded" style="margin-bottom:100px; padding-top:70px; padding-left:70px;">
       <div class="row">
           {% for i in p %}
           <div class="col-sm-4">
  
   <div class="card" style="width: 23rem;">
     <img src="{{i.image.url}}" class="card-img-top p-2" alt=".." height="250px" width="100%">
     <div class="card-body">
       <h4 class="card-title text-center">{{i.name}}</h4>
    <h5 class="text-center">{{i.price}}</h5>
       <a href="{% url 'shop:detail' i.name %}"  class="btn btn-danger" style="position:relative;left:40%; background-color:#80004c;">Details</a>
     </div>
   </div>
   </div>{% endfor %}
   </div></div>
   {% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center><h2 style="color: #80004c">Get the latest offer register now!</h2>
<form method="POST" >
{% csrf_token %}
<center><img src="static/images/login.webp" height="220px" width="480px" class="m-2">

  <div class="col-md-4">
    <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="enter the username">
  </div>

  <div class="col-md-4">
    <label  class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="enter the password">
  </div>

  <div class="col-md-4">
    <label  class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="cp" placeholder="enter the confirm password">
  </div>
    <div class="col-md-4">
    <label  class="form-label">Email</label>
    <input type="Email" class="form-control" name="e" placeholder="enter the email">

  </div>

  <div class="col-md-4"style="padding-top:10px;">

    <input type="submit" class="form-control btn btn-danger " style="background-color:#80004c ">
  </div>
  </form></center>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST" action="/search/search">
  {% csrf_token %}    

<center>
        <div class="text-center"><h4>You Have Searched For  <span class="text-success">{{query}}</span></h4></div>
    </center>

 <div class="container mt-2 rounded rounded-5" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-md-4 mb-4">

<div class="card mb-5" style="width: 25rem;">
  <img src="{{i.image.url}}" class="card-img-top p-2" alt=".." height="250px" width="100%">
  <div class="card-body">
    <h4 class="card-title text-center">{{i.name}}</h4>
 <h5 class="text-center">{{i.price}}</h5>
    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" style="position:relative;left:40%">Details</a>
  </div>
</div></div>
            {% empty %}
            <div class="text-center text-danger"><h4>No Result Found</h4></div>
{% endfor %}
</div></div></form>

{% endblock %}